//! Bundles the Tier 1 runtime into self-contained files.
//!
//! The Service Worker is authored as three ES modules so it can be read and
//! tested, but it must ship as one file. `importScripts` is not an option: pulling
//! the verification core in at runtime would mean executing unverified code to
//! decide whether code is verified. Module workers would avoid that but fail
//! registration outright on engines that lack them, which turns a graceful
//! degradation into a hard outage.
//!
//! So the modules are concatenated here, with a transform small enough to state in
//! full: drop `import` statements between the bundled modules, and strip the
//! `export` keyword from declarations. Nothing is minified or rewritten.

use crate::crypto::TrustRoot;

const VERIFY_MJS: &str = include_str!("../runtime/veilguard-verify.mjs");
const POLICY_MJS: &str = include_str!("../runtime/veilguard-policy.mjs");
const SW_JS: &str = include_str!("../runtime/veil-guard-sw.js");
pub const LOADER_JS: &str = include_str!("../runtime/veil-guard-loader.js");

/// Remove `import ... from '...'` statements and the `export` keyword.
///
/// Only bare-relative imports of the sibling modules are dropped; anything else is
/// left alone so that an unexpected dependency becomes a syntax error in the
/// bundle rather than a silently missing symbol.
///
/// # Why column zero
///
/// The transform acts only on lines that begin `import ` or `export ` with **no
/// leading whitespace**. That is not a formatting preference: `import` and
/// `export` are legal only at a module's top level, so in any reasonably formatted
/// source they sit at column zero, while a line that merely *looks* like one —
/// inside a multi-line template literal, say — is indented or is part of a larger
/// expression. Anchoring to column zero is what keeps this line-based transform
/// from rewriting data that happens to read like code.
///
/// The residual hazard is a multi-line template literal whose continuation line
/// starts at column zero with the word `export`. None of the bundled sources
/// contains one, and `tests/runtime.rs` evaluates the finished bundle to catch
/// structural damage.
pub fn strip_module_syntax(source: &str) -> Result<String, String> {
    let mut out = String::with_capacity(source.len());
    let mut in_import = false;

    for line in source.lines() {
        if in_import {
            // A multi-line import ends at the line carrying the terminating `;`.
            if line.contains(';') {
                in_import = false;
            }
            continue;
        }

        if line.starts_with("import ") {
            if !line.contains(';') {
                in_import = true;
                continue;
            }
            if !(line.contains("'./") || line.contains("\"./")) {
                return Err(format!("unexpected non-local import in runtime source: {line}"));
            }
            continue;
        }

        match line.strip_prefix("export ") {
            Some(rest) => out.push_str(rest),
            None => out.push_str(line),
        }
        out.push('\n');
    }

    if in_import {
        return Err("unterminated import statement in runtime source".into());
    }
    Ok(out)
}

/// Produce the self-contained Service Worker, with `root` baked in as the
/// trust-on-first-use anchor.
pub fn bundle_service_worker(root: &TrustRoot) -> Result<String, String> {
    let root_json = serde_json::to_string(root).map_err(|e| e.to_string())?;

    let mut out = String::new();
    out.push_str(&format!(
        "// veil-guard Tier 1 runtime — generated by veil-guard {}.\n\
         // Do not edit: regenerate with `veil-guard runtime`.\n\
         //\n\
         // Concatenated from runtime/veilguard-verify.mjs, runtime/veilguard-policy.mjs\n\
         // and runtime/veil-guard-sw.js. The trust root below is the anchor this build\n\
         // was signed against; it is adopted on first use and pinned in IndexedDB.\n\
         // Afterwards only a rotation statement signed by the pinned root can move it,\n\
         // so replacing this file does not silently replace the root.\n\n",
        env!("CARGO_PKG_VERSION")
    ));
    out.push_str("'use strict';\n");
    out.push_str(&format!("self.VEIL_GUARD_TRUST_ROOT = {root_json};\n\n"));

    for (name, source) in [
        ("veilguard-verify.mjs", VERIFY_MJS),
        ("veilguard-policy.mjs", POLICY_MJS),
        ("veil-guard-sw.js", SW_JS),
    ] {
        out.push_str(&format!("// ---------- {name} ----------\n"));
        out.push_str(&strip_module_syntax(source)?);
        out.push('\n');
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_exports_and_local_imports() {
        let src = "import { a } from './x.mjs';\nexport const b = 1;\nexport function c() {}\nlet d = 2;\n";
        let out = strip_module_syntax(src).unwrap();
        assert_eq!(out, "const b = 1;\nfunction c() {}\nlet d = 2;\n");
    }

    #[test]
    fn strips_multiline_imports() {
        let src = "import {\n  a,\n  b,\n} from './x.mjs';\nconst z = 1;\n";
        assert_eq!(strip_module_syntax(src).unwrap(), "const z = 1;\n");
    }

    #[test]
    fn leaves_indented_and_embedded_occurrences_alone() {
        // An indented `export` is not valid module syntax, so it is data — most
        // likely a line inside a template literal. It must survive untouched.
        let src = "  export const a = 1;\nconst s = \"export const fake\";\n";
        assert_eq!(strip_module_syntax(src).unwrap(), src);
    }

    #[test]
    fn leaves_indented_imports_alone() {
        let src = "const doc = `\n  import { x } from 'y';\n`;\n";
        assert_eq!(strip_module_syntax(src).unwrap(), src);
    }

    #[test]
    fn rejects_a_dependency_that_is_not_a_sibling_module() {
        let src = "import { x } from 'some-package';\n";
        assert!(strip_module_syntax(src).is_err());
    }

    #[test]
    fn rejects_an_unterminated_import() {
        assert!(strip_module_syntax("import {\n  a,\n").is_err());
    }

    #[test]
    fn bundled_worker_has_no_module_syntax_left() {
        let root: TrustRoot = serde_json::from_str(
            r#"{"threshold":1,"sigalgs":["ed25519"],"keys":[]}"#,
        )
        .unwrap();
        let bundle = bundle_service_worker(&root).unwrap();
        for (i, line) in bundle.lines().enumerate() {
            let t = line.trim_start();
            assert!(!t.starts_with("import "), "line {}: {line}", i + 1);
            assert!(!t.starts_with("export "), "line {}: {line}", i + 1);
        }
        assert!(bundle.contains("self.VEIL_GUARD_TRUST_ROOT = "));
        assert!(bundle.contains("addEventListener('fetch'"));
    }
}
